mod fav_instruments_widget;
pub use fav_instruments_widget::*;
mod select_instrument_panel;
pub use select_instrument_panel::*;
mod render_add_button;
use render_add_button::*;
mod render_instrument;
use render_instrument::*;
mod render_avatar;
pub use render_avatar::*;
mod render_rate;
pub use render_rate::*;
